export const DISEASES = {
  dengue: {
    slug: 'dengue',
    name: 'Dengue Fever',
    vector_name: 'Aedes aegypti',
    vector_type: 'mosquito',
    color_hex: '#F5A623',
    description: 'Mosquito-borne viral infection causing severe flu-like illness.',
    global_at_risk: 3900000000,
    source_paper: 'Brady et al. (2014), PLOS Neglected Tropical Diseases',
    sort_order: 1,
    is_active: true,
  },
  malaria: {
    slug: 'malaria',
    name: 'Malaria',
    vector_name: 'Anopheles gambiae',
    vector_type: 'mosquito',
    color_hex: '#E08B0A',
    description: 'Life-threatening disease transmitted through infected Anopheles mosquitoes.',
    global_at_risk: 3300000000,
    source_paper: 'Ryan et al. (2020), PLOS Biology',
    sort_order: 2,
    is_active: true,
  },
  zika: {
    slug: 'zika',
    name: 'Zika Virus',
    vector_name: 'Aedes aegypti / Aedes albopictus',
    vector_type: 'mosquito',
    color_hex: '#F9BE42',
    description: 'Viral infection spread by mosquitoes, linked to birth defects.',
    global_at_risk: 2600000000,
    source_paper: 'Messina et al. (2016), eLife',
    sort_order: 3,
    is_active: true,
  },
  chikungunya: {
    slug: 'chikungunya',
    name: 'Chikungunya',
    vector_name: 'Aedes albopictus',
    vector_type: 'mosquito',
    color_hex: '#FCD97A',
    description: 'Viral disease causing fever and severe joint pain.',
    global_at_risk: 1300000000,
    source_paper: 'Kraemer et al. (2015), eLife',
    sort_order: 4,
    is_active: true,
  },
  lyme: {
    slug: 'lyme',
    name: 'Lyme Disease',
    vector_name: 'Ixodes ricinus / I. scapularis',
    vector_type: 'tick',
    color_hex: '#8B9CC0',
    description: 'Bacterial infection spread by blacklegged ticks.',
    global_at_risk: 300000000,
    source_paper: 'Estrada-Pena et al. (2014), Ticks and Tick-borne Diseases',
    sort_order: 5,
    is_active: true,
  },
  leishmaniasis: {
    slug: 'leishmaniasis',
    name: 'Leishmaniasis',
    vector_name: 'Phlebotomus papatasi',
    vector_type: 'sandfly',
    color_hex: '#B86D06',
    description: 'Parasitic disease spread by phlebotomine sandflies.',
    global_at_risk: 350000000,
    source_paper: 'Gonzalez et al. (2010), International Journal of Health Geographics',
    sort_order: 6,
    is_active: true,
  },
} as const

export type DiseaseSlug = keyof typeof DISEASES
export const VALID_DISEASES = Object.keys(DISEASES) as DiseaseSlug[]
export const VALID_SCENARIOS = ['SSP1-2.6', 'SSP2-4.5', 'SSP5-8.5'] as const
