DISEASE_PARAMETERS = {
  "dengue": {
    "vector": "Aedes aegypti",
    "paper": "Brady et al. (2014), PLOS Neglected Tropical Diseases",
    "temperature": {"min": 18, "max": 34, "optimal_min": 25, "optimal_max": 30, "winter_min": 10},
    "humidity": {"min": 60},
    "precipitation": {"min_monthly": 50, "required_months": 3},
    "altitude": {"max": 2000},
  },
  "malaria": {
    "vector": "Anopheles gambiae / A. stephensi",
    "paper": "Ryan et al. (2020), PLOS Biology",
    "temperature": {"min": 16, "max": 32, "optimal_min": 20, "optimal_max": 27, "winter_min": 5},
    "humidity": {"min": 60},
    "precipitation": {"min_monthly": 80, "required_months": 4},
    "altitude": {"max": 2500},
  },
  "zika": {
    "vector": "Aedes aegypti / A. albopictus",
    "paper": "Messina et al. (2016), eLife",
    "temperature": {"min": 16, "max": 35, "optimal_min": 24, "optimal_max": 30, "winter_min": 10},
    "humidity": {"min": 55},
    "precipitation": {"min_monthly": 50, "required_months": 3},
    "altitude": {"max": 2200},
  },
  "chikungunya": {
    "vector": "Aedes albopictus (tiger mosquito)",
    "paper": "Kraemer et al. (2015), eLife",
    "temperature": {"min": 10, "max": 36, "optimal_min": 22, "optimal_max": 28, "winter_min": -2},
    "humidity": {"min": 50},
    "precipitation": {"min_monthly": 40, "required_months": 3},
    "altitude": {"max": 2000},
  },
  "lyme": {
    "vector": "Ixodes ricinus / I. scapularis",
    "paper": "Estrada-Pena et al. (2014), Ticks and Tick-borne Diseases",
    "temperature": {"min": 7, "max": 25, "optimal_min": 12, "optimal_max": 20, "winter_min": -15},
    "humidity": {"min": 85},
    "precipitation": {"min_monthly": 60, "required_months": 6},
    "altitude": {"max": 1500},
  },
  "leishmaniasis": {
    "vector": "Phlebotomus papatasi / P. argentipes",
    "paper": "Gonzalez et al. (2010), International Journal of Health Geographics",
    "temperature": {"min": 15, "max": 38, "optimal_min": 25, "optimal_max": 32, "winter_min": 5},
    "humidity": {"min": 40},
    "precipitation": {"min_monthly": 20, "required_months": 2},
    "altitude": {"max": 1700},
  },
}
